[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_chess = "8nS2cyFkip1yibKmJXkzhy6NkVoabUhdLQa9CwhdNWUp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/poz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
